#!/bin/bash

git_get_ver () {
	local OUT=$1
	local N=$2
	echo $OUT | awk "match(\$0, /([0-9]+)\.([0-9]+)\.([0-9]+)/, g) {print g[$N]}"
}

git_set_ver () {
        local OUT=$(git --version 2>&1)
        if [ $? -eq 0 ]; then
		GIT_VER_X=$(git_get_ver "$OUT" 1)
		GIT_VER_Y=$(git_get_ver "$OUT" 2)
		GIT_VER_Z=$(git_get_ver "$OUT" 3)
        fi
}

git_semver_value () {
	git_set_ver
	local GIT_VER_Y3=$GIT_VER_Y
	while [ ${#GIT_VER_Y3} -lt 2 ]; do
		GIT_VER_Y3="0$GIT_VER_Y3"
	done
	echo "$GIT_VER_X$GIT_VER_Y3"
}

if [ $(git_semver_value) -gt 209 ]; then
	echo "Setting up git hooks.."
	git config --local --unset core.hooksPath
	git config --local --add core.hooksPath 'hooks/'
else
	echo "Please upgrade git > 2.9.0"
	git --version
fi

